name: Deployment pipeline

on:
  push:
    branches:
      - main #only check on push to main (which requires a PR)
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      ADMIN_KEY: ${{ secrets.ADMIN_KEY}}
      ENTRY_HASH: ${{ secrets.ENTRY_HASH }}
      ENTRY_KEY: ${{ secrets.ENTRY_KEY }}
      PORT: ${{ secrets.PORT }}
      SECRET_ADMIN: ${{ secrets.SECRET_ADMIN }}
      SECRET_ENTER: ${{ secrets.SECRET_ENTER }}
      SECRET_USER: ${{ secrets.SECRET_USER }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.19'
      - name: Install frontend dependencies
        run: cd frontend && npm install
      - name: Install backend dependencies
        run: cd backend && npm install
      - name: Style check (backend)
        run: cd backend && npm run lint
      - name: Create temporary media folder for testing
        run: cd backend && bash build_temp_media_folder.sh
      - name: Backend integration tests
        run: cd backend && npm run test