name: Daily health check

on:
  schedule:
    - cron: '0 6,16 * * *' #6.00 16.00 and UTC every day
    - cron: '0,15,30,45 * * * *' #Every 15 minutes for testing

jobs: 
  daily_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Health check
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://herrala-bricker-wedding.onrender.com/api/health
          max-attempts: 3
          retry-delay: 10s
